// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnx70B4DW6Rzo3K-laJvQa9iAp8CrUWBo',
    appId: '1:727588511842:web:d62dc2cf697b6873a9313b',
    messagingSenderId: '727588511842',
    projectId: 'cosc4995-ui-1',
    authDomain: 'cosc4995-ui-1.firebaseapp.com',
    storageBucket: 'cosc4995-ui-1.appspot.com',
    measurementId: 'G-DCD9NXFKWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxjk0Nf4zYQxYgSkPZmFv17iP5AOIE-I',
    appId: '1:727588511842:android:8c50f1fc254a9397a9313b',
    messagingSenderId: '727588511842',
    projectId: 'cosc4995-ui-1',
    storageBucket: 'cosc4995-ui-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPPNoXXU7cETMVADlPtdnU4ts_0TWIzos',
    appId: '1:727588511842:ios:4733307a57961614a9313b',
    messagingSenderId: '727588511842',
    projectId: 'cosc4995-ui-1',
    storageBucket: 'cosc4995-ui-1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPPNoXXU7cETMVADlPtdnU4ts_0TWIzos',
    appId: '1:727588511842:ios:4733307a57961614a9313b',
    messagingSenderId: '727588511842',
    projectId: 'cosc4995-ui-1',
    storageBucket: 'cosc4995-ui-1.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
