// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7PHpCIC52M_ypgfGRpi87xSMt_EVNZyo',
    appId: '1:523652369638:web:345a0b71b00a9213c5bf27',
    messagingSenderId: '523652369638',
    projectId: 'passwordmanager-d4a10',
    authDomain: 'passwordmanager-d4a10.firebaseapp.com',
    storageBucket: 'passwordmanager-d4a10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAzit7LvToQyx7rtak6tVHxYoccp1rmI',
    appId: '1:523652369638:android:d9a5f8795c84560cc5bf27',
    messagingSenderId: '523652369638',
    projectId: 'passwordmanager-d4a10',
    storageBucket: 'passwordmanager-d4a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWabj-tXRUo5dJ0mCjg0FZrPmklfpZOs',
    appId: '1:523652369638:ios:fb2736642f60702ec5bf27',
    messagingSenderId: '523652369638',
    projectId: 'passwordmanager-d4a10',
    storageBucket: 'passwordmanager-d4a10.appspot.com',
    iosClientId: '523652369638-m64ff32h055cmhlln93h3dol6st3eqjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWabj-tXRUo5dJ0mCjg0FZrPmklfpZOs',
    appId: '1:523652369638:ios:fb2736642f60702ec5bf27',
    messagingSenderId: '523652369638',
    projectId: 'passwordmanager-d4a10',
    storageBucket: 'passwordmanager-d4a10.appspot.com',
    iosClientId: '523652369638-m64ff32h055cmhlln93h3dol6st3eqjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7PHpCIC52M_ypgfGRpi87xSMt_EVNZyo',
    appId: '1:523652369638:web:a2ae61e533e8b403c5bf27',
    messagingSenderId: '523652369638',
    projectId: 'passwordmanager-d4a10',
    authDomain: 'passwordmanager-d4a10.firebaseapp.com',
    storageBucket: 'passwordmanager-d4a10.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC7PHpCIC52M_ypgfGRpi87xSMt_EVNZyo',
    appId: '1:523652369638:web:73c118e3e0acc10ec5bf27',
    messagingSenderId: '523652369638',
    projectId: 'passwordmanager-d4a10',
    authDomain: 'passwordmanager-d4a10.firebaseapp.com',
    storageBucket: 'passwordmanager-d4a10.appspot.com',
  );
}
